context:
  name: ccxt-py
  version: "4.5.17"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/c/ccxt/ccxt-${{ version }}.tar.gz
  sha256: dc19ff283f86dadc2b194158a5eb2c5b230055883b9f29b35b128b168e5ffa4c

build:
  script: cp README.rst README.md && python -m pip install . -v
  number: 0

requirements:
  host:
    - certifi >=2018.1.18
    - python
    - pip
    - setuptools
  run:
    - aiodns >=1.1.1
    - aiohttp >=3.10.11
    - cryptography >=2.6.1
    - python
    - requests >=2.18.4
    - typing-extensions >=4.4.0
    - yarl
    - if: match(python, ">=3.10")
      then: coincurve 21.*
      else: coincurve 20.*

tests:
  - python:
      imports:
        - ccxt
      pip_check: true

about:
  homepage: https://github.com/ccxt/ccxt
  summary: 'A JavaScript / Python / PHP / C# / Go library for cryptocurrency trading and e-commerce'
  description: |
    The CCXT library is used to connect and trade with cryptocurrency exchanges
    and payment processing services worldwide. It provides quick access to market
    data for storage, analysis, visualization, indicator development, algorithmic
    trading, strategy backtesting, bot programming, and related software engineering.

    It is intended to be used by coders, developers, technically-skilled traders,
    data-scientists and financial analysts for building trading algorithms.
  license: MIT
  license_file: LICENSE.txt
  documentation: https://docs.ccxt.com/
  repository: https://github.com/ccxt/ccxt

extra:
  recipe-maintainers:
    - MementoRC
